In [33]:
#importing libraries
import pandas as pd
import numpy as np
import os

In [34]:
#changing the directory
os.chdir('C:\Projects\Music Recommendation System')

In [35]:
pwd

'C:\\Projects\\Music Recommendation System'

In [36]:
#existing python program
import Recommenders as Recommenders

In [37]:
#loading the data
song_df_1 = pd.read_csv('triplets_file.csv')
print (song_df_1.shape)
print (song_df_1.head())

(2000000, 3)
                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

In [38]:
song_df_2 = pd.read_csv('song_data.csv')
print (song_df_2.shape)
display  (song_df_2.head())

(1000000, 5)

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0

In [39]:
#Combining two data frames to create one data frame
song_df = pd.merge(song_df_1, song_df_2.drop_duplicates(['song_id']), on='song_id', how='left')
display (song_df.shape)
display (song_df.head())

(2000000, 7)

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999

In [40]:
#Display the length of one data frame
print(len(song_df_1), len(song_df_2))
len(song_df)

2000000 1000000

2000000

In [41]:
#improving the performance
song_df = song_df.head(50000)
song_df.shape

(50000, 7)

In [42]:
#creating new features
song_df['song'] = song_df['title']+' - '+song_df['artist_name']
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976,Entre Dos Aguas - Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007,Stronger - Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005,Constellations - Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999,Learn To Fly - Foo Fighters

In [43]:
song_grouped = song_df.groupby(['song']).agg({'listen_count':'count'}).reset_index()
song_grouped.head()

                                                song  listen_count
0  #!*@ You Tonight [Featuring R. Kelly] (Explici...             1
1                           #40 - DAVE MATTHEWS BAND             7
2                                & Down - Boys Noize            13
3                          ' Cello Song - Nick Drake             3
4                        '97 Bonnie & Clyde - Eminem             5

In [44]:
grouped_sum = song_grouped['listen_count'].sum()
grouped_sum

50000

In [45]:
song_grouped['percentage'] = (song_grouped['listen_count'] / grouped_sum ) * 100
song_grouped.sort_values(['listen_count', 'song'], ascending=[0,1])

,song,listen_count,percentage
6682,Sehr kosmisch - Harmonia,204,0.408
8509,Undo - Björk,182,0.364
1936,Dog Days Are Over (Radio Edit) - Florence + Th...,173,0.346
9256,You're The One - Dwight Yoakam,169,0.338
6348,Revelry - Kings Of Leon,166,0.332
...,...,...,...
9290,Your Time Has Come - Audioslave,1,0.002
9300,Zebra (full-length/album version) - John Butle...,1,0.002
9311,clouding - Four Tet,1,0.002
9312,high fives - Four Tet,1,0.002
9321,the Love Song - K-OS,1,0.002

In [46]:
#Popularity Recommendation Engine
pr = Recommenders.popularity_recommender_py()
pr.create(song_df, 'user_id', 'song')

In [47]:
pr.recommend(song_df['user_id'][5])

,user_id,song,score,Rank
6682,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Sehr kosmisch - Harmonia,204,1.0
8509,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Undo - Björk,182,2.0
1936,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Dog Days Are Over (Radio Edit) - Florence + Th...,173,3.0
9256,b80344d063b5ccb3212f76538f3d9e43d87dca9e,You're The One - Dwight Yoakam,169,4.0
6348,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Revelry - Kings Of Leon,166,5.0
6671,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Secrets - OneRepublic,158,6.0
3372,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Horn Concerto No. 4 in E flat K495: II. Romanc...,134,7.0
2532,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Fireflies - Charttraxx Karaoke,128,8.0
8287,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Tive Sim - Cartola,117,9.0
3254,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Hey_ Soul Sister - Train,109,10.0

In [48]:
pr.recommend(song_df['user_id'][100])

,user_id,song,score,Rank
6682,e006b1a48f466bf59feefed32bec6494495a4436,Sehr kosmisch - Harmonia,204,1.0
8509,e006b1a48f466bf59feefed32bec6494495a4436,Undo - Björk,182,2.0
1936,e006b1a48f466bf59feefed32bec6494495a4436,Dog Days Are Over (Radio Edit) - Florence + Th...,173,3.0
9256,e006b1a48f466bf59feefed32bec6494495a4436,You're The One - Dwight Yoakam,169,4.0
6348,e006b1a48f466bf59feefed32bec6494495a4436,Revelry - Kings Of Leon,166,5.0
6671,e006b1a48f466bf59feefed32bec6494495a4436,Secrets - OneRepublic,158,6.0
3372,e006b1a48f466bf59feefed32bec6494495a4436,Horn Concerto No. 4 in E flat K495: II. Romanc...,134,7.0
2532,e006b1a48f466bf59feefed32bec6494495a4436,Fireflies - Charttraxx Karaoke,128,8.0
8287,e006b1a48f466bf59feefed32bec6494495a4436,Tive Sim - Cartola,117,9.0
3254,e006b1a48f466bf59feefed32bec6494495a4436,Hey_ Soul Sister - Train,109,10.0

In [49]:
#Item Similarity Recommendation
ir = Recommenders.item_similarity_recommender_py()
ir.create(song_df, 'user_id', 'song')

In [50]:
user_items = ir.get_user_items(song_df['user_id'][5])
for user_item in user_items:
    print(user_item)

The Cove - Jack Johnson
Entre Dos Aguas - Paco De Lucia
Stronger - Kanye West
Constellations - Jack Johnson
Learn To Fly - Foo Fighters
Apuesta Por El Rock 'N' Roll - Héroes del Silencio
Paper Gangsta - Lady GaGa
Stacked Actors - Foo Fighters
Sehr kosmisch - Harmonia
Heaven's gonna burn your eyes - Thievery Corporation feat. Emiliana Torrini
Let It Be Sung - Jack Johnson / Matt Costa / Zach Gill / Dan Lebowitz / Steve Adams
I'll Be Missing You (Featuring Faith Evans & 112)(Album Version) - Puff Daddy
Love Shack - The B-52's
Clarity - John Mayer
I?'m A Steady Rollin? Man - Robert Johnson
The Old Saloon - The Lonely Island
Behind The Sea [Live In Chicago] - Panic At The Disco
Champion - Kanye West
Breakout - Foo Fighters
Ragged Wood - Fleet Foxes
Mykonos - Fleet Foxes
Country Road - Jack Johnson / Paula Fuga
Oh No - Andrew Bird
Love Song For No One - John Mayer
Jewels And Gold - Angus & Julia Stone
Warning - Incubus
83 - John Mayer
Neon - John Mayer
The Middle - Jimmy Eat World
High and dry - Jorge Drexler
All That We Perceive - Thievery Corporation
The Christmas Song  (LP Version) - King Curtis
Our Swords (Soundtrack Version) - Band Of Horses
Are You In? - Incubus
Drive - Incubus
Generator - Foo Fighters
Come Back To Bed - John Mayer
He Doesn't Know Why - Fleet Foxes
Trani - Kings Of Leon
Bigger Isn't Better - The String Cheese Incident
Sun Giant - Fleet Foxes
City Love - John Mayer
Right Back - Sublime
Moonshine - Jack Johnson
Holes To Heaven - Jack Johnson

In [51]:
user_items = ir.get_user_items(song_df['user_id'][70])
for user_item in user_items:
    print(user_item)

A Pain That Im Used To - Depeche Mode
Medicating - Boys Night Out
Crystal Blue Persuasion - Tommy James And The Shondells
Don't Dream It's Over - Crowded House
Jamaica Roots II(Agora E Sempre) - Natiruts
Besame Mucho - Andrea Bocelli
Groovin'  (LP Version) - Booker T. & The MG's
It's My Party - Lesley Gore
Eminence Front - The Who
Mr. Jones - Counting Crows
You Get What You Give - New Radicals
Groovin'  (Single Version) - The Young Rascals
We Don't Stop (Explicit) - Young Bleed
The Waiting - Tom Petty And The Heartbreakers
Found Home - 59 Times the Pain
Reasons - Minnie Riperton
Heartbreak Warfare - John Mayer
Who's Real - Jadakiss / Swizz Beatz / OJ Da Juiceman
All My Friends - LCD Soundsystem

In [52]:
ir.recommend(song_df['user_id'][5])

No. of unique songs for the user: 45
no. of unique songs in the training set: 9325
Non zero values in cooccurence_matrix :27764

,user_id,song,score,rank
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Questions - Jack Johnson,0.037157,1
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Great Indoors - John Mayer,0.036953,2
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Wrong Turn - Jack Johnson,0.036740,3
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Ghost Dream - Hymie's Basement,0.036463,4
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Baby I Want You - Amos Lee,0.036244,5
5,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Better That We Break - Maroon 5,0.035016,6
6,b80344d063b5ccb3212f76538f3d9e43d87dca9e,The Sharing Song - Jack Johnson,0.034193,7
7,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Better Days - Amos Lee,0.034193,8
8,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Dreamin' - Amos Lee,0.034193,9
9,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Mr.Curiosity (Album Version) - Jason Mraz,0.034193,10

In [53]:
ir.recommend(song_df['user_id'][70])

No. of unique songs for the user: 19
no. of unique songs in the training set: 9325
Non zero values in cooccurence_matrix :10172

,user_id,song,score,rank
0,969cc6fb74e076a68e36a04409cb9d3765757508,The Power of Love - Frankie Goes To Hollywood,0.037531,1
1,969cc6fb74e076a68e36a04409cb9d3765757508,Get Innocuous! - LCD Soundsystem,0.035540,2
2,969cc6fb74e076a68e36a04409cb9d3765757508,Nostalgia - The Long Blondes,0.030364,3
3,969cc6fb74e076a68e36a04409cb9d3765757508,Subbacultcha - Pixies,0.030364,4
4,969cc6fb74e076a68e36a04409cb9d3765757508,Under The Falling Sky (LP Version) - Jackson B...,0.030364,5
5,969cc6fb74e076a68e36a04409cb9d3765757508,Good Days Bad Days - Kaiser Chiefs,0.030364,6
6,969cc6fb74e076a68e36a04409cb9d3765757508,Blister In The Sun - Violent Femmes,0.030364,7
7,969cc6fb74e076a68e36a04409cb9d3765757508,North American Scum - LCD Soundsystem,0.029984,8
8,969cc6fb74e076a68e36a04409cb9d3765757508,Girls On Film - Duran Duran,0.026610,9
9,969cc6fb74e076a68e36a04409cb9d3765757508,Enterlude - The Killers,0.026564,10

In [54]:
#Recommendation based on Song Name 
ir.get_similar_items(['Use Somebody - Kings Of Leon'])

no. of unique songs in the training set: 9325
Non zero values in cooccurence_matrix :3031

  user_id                                               song     score  rank
0                            OMG - Usher featuring will.i.am  0.233333     1
1          Lucky (Album Version) - Jason Mraz & Colbie Ca...  0.227941     2
2                                           Marry Me - Train  0.225610     3
3                                   The Scientist - Coldplay  0.222930     4
4                                   Hey_ Soul Sister - Train  0.221557     5
5                        Drop The World - Lil Wayne / Eminem  0.216561     6
6                                      Secrets - OneRepublic  0.210526     7
7                            Heartbreak Warfare - John Mayer  0.208000     8
8                             Fireflies - Charttraxx Karaoke  0.205405     9
9                           Somebody To Love - Justin Bieber  0.204380    10

In [55]:
ir.get_similar_items(['Somebody to love','Justin Bieber'])

no. of unique songs in the training set: 9325
Non zero values in cooccurence_matrix :0

  user_id                                               song  score  rank
0                                              Rapture - iio    0.0     1
1          King Of My Castle [Nicola Fasano & Steve Fores...    0.0     2
2                         One More Step To Take - Delegation    0.0     3
3                         How It Makes You Feel - Jill Scott    0.0     4
4               Fuori Dal Tunnel (Album Version) - Caparezza    0.0     5
5                         Shooter - Robin Thicke / Lil Wayne    0.0     6
6                              Break Up To Make Up - Jeremih    0.0     7
7                            Opus No. 12 - Dustin O'Halloran    0.0     8
8                              Watch Over You - Alter Bridge    0.0     9
9                                            Arise - Flyleaf    0.0    10